version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: my-next-app:latest # 指定要運行的 image
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_EMAIL: NEXT_PUBLIC_EMAIL_local_email
      email: local_email
